/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthResult = { 'ok' : null } |
  { 'err' : Error };
export type Error = { 'roleNotSet' : null } |
  { 'recruiterCannotApply' : null } |
  { 'noApplicationFound' : null } |
  { 'alreadyRegistered' : null } |
  { 'jobSeekerCannotSearch' : null } |
  { 'unauthorized' : null } |
  { 'invalidCredentials' : null } |
  { 'roleAlreadySet' : null } |
  { 'profileNotFound' : null };
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface JobApplicantProfile {
  'userId' : Principal,
  'name' : string,
  'email' : string,
  'gender' : Gender,
  'phone' : string,
  'photo' : [] | [ExternalBlob],
  'location' : Location,
}
export type JobApplicationResult = { 'ok' : JobApplicantProfile } |
  { 'err' : Error };
export type JobApplicationsResult = { 'ok' : Array<JobApplicantProfile> } |
  { 'err' : Error };
export interface Location {
  'country' : string,
  'city' : string,
  'district' : string,
  'state' : string,
}
export type Principal = Principal;
export type RegisterResult = { 'ok' : Principal } |
  { 'err' : Error };
export interface UserProfile {
  'name' : string,
  'role' : [] | [UserRole],
  'email' : string,
  'gender' : Gender,
  'onboardingCompleted' : boolean,
  'phone' : string,
  'location' : [] | [Location],
}
export type UserRole = { 'jobSeeker' : null } |
  { 'recruiter' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VoidResult = { 'ok' : null } |
  { 'err' : Error };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'authenticateUser' : ActorMethod<[string, string], AuthResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyJobApplication' : ActorMethod<[], JobApplicationResult>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[UserProfile, string], RegisterResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchApplicantsByLocation' : ActorMethod<
    [Location, boolean],
    JobApplicationsResult
  >,
  'setUserLocation' : ActorMethod<[Location], VoidResult>,
  'setUserRole' : ActorMethod<[UserRole], VoidResult>,
  'submitJobApplication' : ActorMethod<[Location, ExternalBlob], VoidResult>,
  'updateJobApplication' : ActorMethod<[Location, ExternalBlob], VoidResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];