/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'jobSeeker' : IDL.Null,
  'recruiter' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Location = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Opt(UserRole),
  'email' : IDL.Text,
  'gender' : Gender,
  'onboardingCompleted' : IDL.Bool,
  'phone' : IDL.Text,
  'location' : IDL.Opt(Location),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const JobApplicantProfile = IDL.Record({
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : Location,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'authenticateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyJobApplication' : IDL.Func(
      [],
      [IDL.Opt(JobApplicantProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([UserProfile, IDL.Text], [IDL.Principal], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchApplicantsByLocation' : IDL.Func(
      [Location, IDL.Bool],
      [IDL.Vec(JobApplicantProfile)],
      ['query'],
    ),
  'setUserLocation' : IDL.Func([Location], [], []),
  'setUserRole' : IDL.Func([UserRole], [], []),
  'submitJobApplication' : IDL.Func([Location, ExternalBlob], [], []),
  'updateJobApplication' : IDL.Func([Location, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'jobSeeker' : IDL.Null,
    'recruiter' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Location = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Opt(UserRole),
    'email' : IDL.Text,
    'gender' : Gender,
    'onboardingCompleted' : IDL.Bool,
    'phone' : IDL.Text,
    'location' : IDL.Opt(Location),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const JobApplicantProfile = IDL.Record({
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : Location,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'authenticateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyJobApplication' : IDL.Func(
        [],
        [IDL.Opt(JobApplicantProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([UserProfile, IDL.Text], [IDL.Principal], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchApplicantsByLocation' : IDL.Func(
        [Location, IDL.Bool],
        [IDL.Vec(JobApplicantProfile)],
        ['query'],
      ),
    'setUserLocation' : IDL.Func([Location], [], []),
    'setUserRole' : IDL.Func([UserRole], [], []),
    'submitJobApplication' : IDL.Func([Location, ExternalBlob], [], []),
    'updateJobApplication' : IDL.Func([Location, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };